Update playground2.yml

diff --git a/.github/workflows/playground2.yml b/.github/workflows/playground2.yml
--- a/.github/workflows/playground2.yml
+++ b/.github/workflows/playground2.yml
@@ -30,5 +30,4 @@ jobs:
             - add a changelog entry
             - add `[skip changelog]` to the PR title
             - label the PR with `skip/changelog`
-        run: |
-          echo "::error::${MESSAGE//$'\n'/%0A}"
+        run: echo "::error::${MESSAGE//$'\n'/%0A}" && exit 1
